# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pouch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pouch
	pod 'Swinject'
	pod 'ObjectMapper'
	pod 'RxSwift'
    	pod 'RxCocoa'
	pod 'Alamofire'
	pod 'FSCalendar'

  target 'PouchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PouchUITests' do
    # Pods for testing
  end

end
